server:
  port: 8081
spring:
  datasource:
    username: root
    password: promiseme10@
    url: jdbc:mysql://localhost:3306/yygh_hosp?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher