server:
  port: 8081
spring:
  datasource:
    username: root
    password: promiseme10@
    url: jdbc:mysql://localhost:3306/yygh_hosp?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      server-addr: localhost:8848
  application:
    name: Hospital-System

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

